/**
 * Keepit Mock Data - Products
 * 25 realistic products distributed across categories
 */

import { Product } from "@/types/keepit"

export const MOCK_PRODUCTS: Product[] = [
  // ALIMENTOS (8 products)
  {
    id: "prod-1",
    name: "Big Mac Combo",
    description: "Big Mac + Batata Média + Refrigerante Médio",
    price: 32.90,
    images: ["/template-images/products/product-img1.png"],
    thumbnail: "/template-images/products/product-img1.png",
    vendorId: "vendor-3",
    category: "alimentos",
    hosterIds: ["hoster-1", "hoster-2", "hoster-3", "hoster-4"],
    featured: true,
    badge: "bestseller",
    stock: 50,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: "prod-2",
    name: "Caixa de Bombons Cacau Show 250g",
    description: "Bombons sortidos de chocolate belga. Perfeito para presente.",
    price: 45.00,
    originalPrice: 59.90,
    images: ["/template-images/products/product-img2.png"],
    thumbnail: "/template-images/products/product-img2.png",
    vendorId: "vendor-4",
    category: "alimentos",
    hosterIds: ["hoster-4", "hoster-7"],
    featured: true,
    badge: "promotion",
    stock: 30,
    rating: 4.8,
    reviewCount: 85,
  },
  {
    id: "prod-3",
    name: "Subway Frango Teriyaki 30cm",
    description: "Sanduíche de 30cm com frango grelhado e molho teriyaki.",
    price: 28.50,
    images: ["/template-images/products/product-img3.png"],
    thumbnail: "/template-images/products/product-img3.png",
    vendorId: "vendor-5",
    category: "alimentos",
    hosterIds: ["hoster-1", "hoster-2", "hoster-6"],
    featured: false,
    stock: 40,
    rating: 4.3,
    reviewCount: 62,
  },
  {
    id: "prod-4",
    name: "Bob's Milkshake Ovomaltine 500ml",
    description: "O famoso milkshake de ovomaltine do Bob's.",
    price: 18.90,
    images: ["/template-images/products/product-img4.png"],
    thumbnail: "/template-images/products/product-img4.png",
    vendorId: "vendor-8",
    category: "alimentos",
    hosterIds: ["hoster-3", "hoster-5", "hoster-7"],
    featured: false,
    badge: "bestseller",
    stock: 60,
    rating: 4.9,
    reviewCount: 210,
  },
  {
    id: "prod-5",
    name: "Spoleto Massa Fresca Penne ao Molho Rosé",
    description: "Penne ao molho rosé com opção de proteína (frango ou camarão).",
    price: 35.90,
    images: ["/template-images/products/product-img5.png"],
    thumbnail: "/template-images/products/product-img5.png",
    vendorId: "vendor-12",
    category: "alimentos",
    hosterIds: ["hoster-2", "hoster-4", "hoster-6"],
    featured: false,
    stock: 25,
    rating: 4.6,
    reviewCount: 94,
  },
  {
    id: "prod-6",
    name: "Outback Bloomin' Onion",
    description: "A famosa cebola empanada gigante com molho especial.",
    price: 42.00,
    images: ["/template-images/products/product-img6.png"],
    thumbnail: "/template-images/products/product-img6.png",
    vendorId: "vendor-13",
    category: "alimentos",
    hosterIds: ["hoster-4", "hoster-7"],
    featured: true,
    badge: "exclusive",
    stock: 20,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: "prod-7",
    name: "Barra de Proteína Mundo Verde - Chocolate",
    description: "Barra de proteína vegana com 20g de proteína.",
    price: 8.90,
    images: ["/template-images/products/product-img7.png"],
    thumbnail: "/template-images/products/product-img7.png",
    vendorId: "vendor-15",
    category: "alimentos",
    hosterIds: ["hoster-2", "hoster-5", "hoster-6"],
    featured: false,
    badge: "new",
    stock: 100,
    rating: 4.4,
    reviewCount: 43,
  },
  {
    id: "prod-8",
    name: "Pão de Açúcar Torta de Limão 450g",
    description: "Torta de limão artesanal com merengue italiano.",
    price: 29.90,
    images: ["/template-images/products/product-img8.png"],
    thumbnail: "/template-images/products/product-img8.png",
    vendorId: "vendor-1",
    category: "alimentos",
    hosterIds: ["hoster-1", "hoster-2", "hoster-4", "hoster-7"],
    featured: false,
    stock: 15,
    rating: 4.8,
    reviewCount: 72,
  },

  // BEBIDAS (5 products)
  {
    id: "prod-9",
    name: "Coca-Cola 2L",
    description: "Refrigerante de cola tradicional em garrafa de 2 litros.",
    price: 9.90,
    images: ["/template-images/products/product-img9.png"],
    thumbnail: "/template-images/products/product-img9.png",
    vendorId: "vendor-9",
    category: "bebidas",
    hosterIds: ["hoster-1", "hoster-2", "hoster-3", "hoster-4", "hoster-5", "hoster-6", "hoster-7"],
    featured: true,
    badge: "bestseller",
    stock: 200,
    rating: 4.7,
    reviewCount: 543,
  },
  {
    id: "prod-10",
    name: "Starbucks Frappuccino Caramelo",
    description: "Bebida gelada com café expresso, leite e caramelo.",
    price: 24.50,
    images: ["/template-images/products/product-img10.png"],
    thumbnail: "/template-images/products/product-img10.png",
    vendorId: "vendor-10",
    category: "bebidas",
    hosterIds: ["hoster-2", "hoster-4", "hoster-5"],
    featured: true,
    stock: 35,
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: "prod-11",
    name: "Coca-Cola Zero 350ml (Pack com 6)",
    description: "Pack com 6 latas de Coca-Cola Zero Açúcar.",
    price: 15.90,
    originalPrice: 19.90,
    images: ["/template-images/products/product-img11.png"],
    thumbnail: "/template-images/products/product-img11.png",
    vendorId: "vendor-9",
    category: "bebidas",
    hosterIds: ["hoster-1", "hoster-3", "hoster-6", "hoster-7"],
    featured: false,
    badge: "promotion",
    stock: 150,
    rating: 4.5,
    reviewCount: 234,
  },
  {
    id: "prod-12",
    name: "Starbucks Pike Place Roast - Grãos 250g",
    description: "Café em grãos torrado médio, equilibrado e suave.",
    price: 42.00,
    images: ["/template-images/products/product-img12.png"],
    thumbnail: "/template-images/products/product-img12.png",
    vendorId: "vendor-10",
    category: "bebidas",
    hosterIds: ["hoster-2", "hoster-4", "hoster-5"],
    featured: false,
    badge: "new",
    stock: 45,
    rating: 4.8,
    reviewCount: 97,
  },
  {
    id: "prod-13",
    name: "Suco Natural Del Valle Laranja 1L",
    description: "Suco de laranja 100% natural sem conservantes.",
    price: 12.90,
    images: ["/template-images/products/product-img13.png"],
    thumbnail: "/template-images/products/product-img13.png",
    vendorId: "vendor-9",
    category: "bebidas",
    hosterIds: ["hoster-1", "hoster-2", "hoster-4", "hoster-7"],
    featured: false,
    stock: 80,
    rating: 4.3,
    reviewCount: 118,
  },

  // MERCADO (4 products)
  {
    id: "prod-14",
    name: "Pão de Açúcar Arroz Integral 1kg",
    description: "Arroz integral tipo 1, rico em fibras.",
    price: 11.90,
    images: ["/template-images/products/product-img14.png"],
    thumbnail: "/template-images/products/product-img14.png",
    vendorId: "vendor-1",
    category: "mercado",
    hosterIds: ["hoster-1", "hoster-2", "hoster-4", "hoster-7"],
    featured: false,
    stock: 120,
    rating: 4.4,
    reviewCount: 76,
  },
  {
    id: "prod-15",
    name: "Pão de Açúcar Azeite Extra Virgem 500ml",
    description: "Azeite de oliva extra virgem importado de Portugal.",
    price: 35.90,
    images: ["/template-images/products/product-img15.png"],
    thumbnail: "/template-images/products/product-img15.png",
    vendorId: "vendor-1",
    category: "mercado",
    hosterIds: ["hoster-1", "hoster-2", "hoster-4", "hoster-7"],
    featured: true,
    badge: "exclusive",
    stock: 60,
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: "prod-16",
    name: "Kit Limpeza Completo Pão de Açúcar",
    description: "Kit com detergente, esponja, desinfetante e água sanitária.",
    price: 28.50,
    originalPrice: 35.00,
    images: ["/template-images/products/product-img16.png"],
    thumbnail: "/template-images/products/product-img16.png",
    vendorId: "vendor-1",
    category: "mercado",
    hosterIds: ["hoster-1", "hoster-2", "hoster-4", "hoster-7"],
    featured: false,
    badge: "promotion",
    stock: 85,
    rating: 4.2,
    reviewCount: 54,
  },
  {
    id: "prod-17",
    name: "Pão de Açúcar Café Premium Moído 500g",
    description: "Café premium torrado e moído, 100% arábica.",
    price: 22.90,
    images: ["/template-images/products/product-img17.png"],
    thumbnail: "/template-images/products/product-img17.png",
    vendorId: "vendor-1",
    category: "mercado",
    hosterIds: ["hoster-1", "hoster-2", "hoster-4", "hoster-7"],
    featured: false,
    stock: 95,
    rating: 4.7,
    reviewCount: 168,
  },

  // FARMÁCIA (4 products)
  {
    id: "prod-18",
    name: "Drogasil Dipirona 500mg - 20 comprimidos",
    description: "Analgésico e antitérmico para dor e febre.",
    price: 8.50,
    images: ["/template-images/products/product-img18.png"],
    thumbnail: "/template-images/products/product-img18.png",
    vendorId: "vendor-2",
    category: "farmacia",
    hosterIds: ["hoster-2", "hoster-3", "hoster-5", "hoster-6"],
    featured: false,
    stock: 150,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: "prod-19",
    name: "Natura Chronos Creme Anti-Idade 40ml",
    description: "Creme facial com ação anti-idade e hidratante.",
    price: 89.90,
    images: ["/template-images/products/product-img19.png"],
    thumbnail: "/template-images/products/product-img19.png",
    vendorId: "vendor-11",
    category: "farmacia",
    hosterIds: ["hoster-4", "hoster-5", "hoster-7"],
    featured: true,
    badge: "new",
    stock: 40,
    rating: 4.8,
    reviewCount: 127,
  },
  {
    id: "prod-20",
    name: "Drogasil Kit Higiene Bucal Completo",
    description: "Escova de dente, pasta, fio dental e enxaguante bucal.",
    price: 45.00,
    originalPrice: 55.00,
    images: ["/template-images/products/product-img20.png"],
    thumbnail: "/template-images/products/product-img20.png",
    vendorId: "vendor-2",
    category: "farmacia",
    hosterIds: ["hoster-2", "hoster-3", "hoster-5", "hoster-6"],
    featured: false,
    badge: "promotion",
    stock: 70,
    rating: 4.5,
    reviewCount: 103,
  },
  {
    id: "prod-21",
    name: "Natura Tododia Hidratante Corporal 400ml",
    description: "Loção hidratante com fragrância de flor de cerejeira.",
    price: 39.90,
    images: ["/template-images/products/popular-img1.png"],
    thumbnail: "/template-images/products/popular-img1.png",
    vendorId: "vendor-11",
    category: "farmacia",
    hosterIds: ["hoster-4", "hoster-5", "hoster-7"],
    featured: false,
    stock: 55,
    rating: 4.7,
    reviewCount: 198,
  },

  // ELETRÔNICOS (4 products)
  {
    id: "prod-22",
    name: "Havaianas Top Mix Azul",
    description: "Chinelo Havaianas clássico, confortável e durável.",
    price: 29.90,
    images: ["/template-images/products/popular-img2.png"],
    thumbnail: "/template-images/products/popular-img2.png",
    vendorId: "vendor-6",
    category: "eletronicos",
    hosterIds: ["hoster-4", "hoster-7"],
    featured: false,
    stock: 80,
    rating: 4.8,
    reviewCount: 342,
  },
  {
    id: "prod-23",
    name: "iPlace AirPods Pro 2ª Geração",
    description: "Fones de ouvido com cancelamento ativo de ruído e áudio espacial.",
    price: 2299.00,
    images: ["/template-images/products/popular-img3.png"],
    thumbnail: "/template-images/products/popular-img3.png",
    vendorId: "vendor-14",
    category: "eletronicos",
    hosterIds: ["hoster-2", "hoster-4"],
    featured: true,
    badge: "exclusive",
    stock: 25,
    rating: 4.9,
    reviewCount: 267,
  },
  {
    id: "prod-24",
    name: "Americanas JBL Flip 5 Caixa Bluetooth",
    description: "Caixa de som portátil à prova d'água com 12h de bateria.",
    price: 549.00,
    originalPrice: 699.00,
    images: ["/template-images/products/popular-img4.png"],
    thumbnail: "/template-images/products/popular-img4.png",
    vendorId: "vendor-7",
    category: "eletronicos",
    hosterIds: ["hoster-2", "hoster-4", "hoster-6"],
    featured: true,
    badge: "promotion",
    stock: 35,
    rating: 4.7,
    reviewCount: 421,
  },
  {
    id: "prod-25",
    name: "iPlace Cabo USB-C para Lightning 1m",
    description: "Cabo original Apple para carregamento rápido.",
    price: 159.00,
    images: ["/template-images/products/popular-img5.png"],
    thumbnail: "/template-images/products/popular-img5.png",
    vendorId: "vendor-14",
    category: "eletronicos",
    hosterIds: ["hoster-2", "hoster-4"],
    featured: false,
    stock: 100,
    rating: 4.5,
    reviewCount: 186,
  },
]

export const getProductById = (id: string): Product | undefined => {
  return MOCK_PRODUCTS.find((product) => product.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  return MOCK_PRODUCTS.filter(
    (product) => product.category.toLowerCase() === category.toLowerCase()
  )
}

export const getProductsByVendor = (vendorId: string): Product[] => {
  return MOCK_PRODUCTS.filter((product) => product.vendorId === vendorId)
}

export const getProductsByHoster = (hosterId: string): Product[] => {
  return MOCK_PRODUCTS.filter((product) => product.hosterIds.includes(hosterId))
}

export const getFeaturedProducts = (): Product[] => {
  return MOCK_PRODUCTS.filter((product) => product.featured === true)
}

export const getProductsByBadge = (badge: Product["badge"]): Product[] => {
  return MOCK_PRODUCTS.filter((product) => product.badge === badge)
}

export const getProductsWithDiscount = (): Product[] => {
  return MOCK_PRODUCTS.filter(
    (product) => product.originalPrice && product.originalPrice > product.price
  )
}
