// Mock data for popular products
export const popularProducts = [
  {
    title: 'Organic Bananas',
    imgSrc: '/images/product/1.png',
    rating: 4.5,
    reviews: 120,
    price: 3.99,
    categories: 'All',
  },
  {
    title: 'Fresh Strawberries',
    imgSrc: '/images/product/2.png',
    rating: 5,
    reviews: 85,
    price: 6.99,
    discount: 10,
    oldPrice: 7.99,
    badge: 'New',
    categories: 'New arrivals',
  },
  {
    title: 'Organic Honey',
    imgSrc: '/images/product/3.png',
    rating: 4.8,
    reviews: 200,
    price: 12.99,
    categories: 'Features',
  },
  {
    title: 'Whole Grain Bread',
    imgSrc: '/images/product/4.png',
    rating: 4.3,
    reviews: 95,
    price: 4.49,
    categories: 'Best sellers',
  },
  {
    title: 'Fresh Milk',
    imgSrc: '/images/product/5.png',
    rating: 4.7,
    reviews: 150,
    price: 5.99,
    categories: 'All',
  },
  {
    title: 'Greek Yogurt',
    imgSrc: '/images/product/6.png',
    rating: 4.6,
    reviews: 110,
    price: 7.49,
    categories: 'New arrivals',
  },
  {
    title: 'Organic Eggs',
    imgSrc: '/images/product/7.png',
    rating: 4.9,
    reviews: 180,
    price: 8.99,
    categories: 'Features',
  },
  {
    title: 'Fresh Salmon',
    imgSrc: '/images/product/8.png',
    rating: 4.4,
    reviews: 75,
    price: 15.99,
    categories: 'Best sellers',
  },
];
